services:
  - type: web
    name: ekyc-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: "https://your-backend-url.onrender.com"
